name: Bug Report
description: Report a bug in the DIDComm V2 Mediator Test Suite

body:
  - type: dropdown
    id: is-regression
    attributes:
      label: Is this a regression?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: input
    id: reproduction
    attributes:
      label: Please provide a link to a minimal reproduction of the bug

  - type: textarea
    id: exception-or-error
    attributes:
      label: Please provide the exception or error you saw
      render: true

  - type: textarea
    id: environment
    attributes:
      label: Please provide the environment you discovered this bug in (run `ng version`)
      render: true

  - type: textarea
    id: other
    attributes:
      label: Anything else?
